use IPL;

CREATE TABLE team
(
    team_id INTEGER NOT NULL PRIMARY KEY,
    team_name VARCHAR(100) NOT NULL UNIQUE
)

INSERT INTO team (team_id,team_name) VALUES
(1,'Royal Challengers Bengaluru'),
(2,'Chennai Super Kings');

SELECT * FROM team;

CREATE TABLE player (
    player_id INTEGER NOT NULL PRIMARY KEY,
    player_name VARCHAR(100) NOT NULL,
    team_id INTEGER NOT NULL,
    FOREIGN KEY (team_id) REFERENCES team(team_id)
)

INSERT INTO player VALUES(1,'V Kohli',1);
INSERT INTO player VALUES(2,'F du Plessis',1);
INSERT INTO player VALUES(3,'RM Patidar',1);
INSERT INTO player VALUES(4,'GJ Maxwell',1);
INSERT INTO player VALUES(5,'C Green',1);
INSERT INTO player VALUES(6,'Anuj Rawat',1);
INSERT INTO player VALUES(7,'KD Karthik',1);
INSERT INTO player VALUES(8,'KV Sharma',1);
INSERT INTO player VALUES(9,'AS Joseph',1);
INSERT INTO player VALUES(10,'Mayank Dagar',1);
INSERT INTO player VALUES(11,'Mohammed Siraj',1);
INSERT INTO player VALUES(12,'Yash Dayal',1);
INSERT INTO player VALUES(13,'RD Gaikwad',2);
INSERT INTO player VALUES(14,'R Ravindra',2);
INSERT INTO player VALUES(15,'AM Rahane',2);
INSERT INTO player VALUES(16,'DJ Mitchell',2);
INSERT INTO player VALUES(17,'S Dube',2);
INSERT INTO player VALUES(18,'RA Jadeja',2);
INSERT INTO player VALUES(19,'Sameer Rizvi',2);
INSERT INTO player VALUES(20,'MS Dhoni',2);
INSERT INTO player VALUES(21,'DL Chahar',2);
INSERT INTO player VALUES(22,'M Theekshana',2);
INSERT INTO player VALUES(23,'TU Deshpande',2);
INSERT INTO player VALUES(24,'Mustafizur Rahman',2);

SELECT * from player;

-- Create the match table

CREATE table `match` (
    match_id INTEGER NOT NULL PRIMARY KEY,
    match_date VARCHAR(10) NOT NULL,
    venue_id INTEGER NOT NULL,
    FOREIGN KEY (venue_id) REFERENCES venue(venue_id)
)

INSERT INTO `match` VALUES(1,'2024-03-22',1);

-- Create the innings table
CREATE TABLE innings
(    match_id    INTEGER NOT NULL,
     innings_no   INTEGER NOT NULL,
     batting_team_id    INTEGER  NOT NULL ,
     bowling_team_id   INTEGER NOT NULL ,
     PRIMARY KEY (match_id, innings_no),
     FOREIGN KEY (batting_team_id) REFERENCES team(team_id),
     FOREIGN KEY (bowling_team_id) REFERENCES team(team_id)
);

INSERT INTO innings VALUES(1,1,1,2);
INSERT INTO innings VALUES(1,2,2,1);

SELECT * FROM innings;

-- Create the score_by_ball table
CREATE TABLE score_by_ball
(   match_id    INTEGER ,
    innings_no   INTEGER ,
    ball_no    FLOAT ,
    striker_id   INTEGER  ,
    non_striker_id   INTEGER  ,
    bowler_id    INTEGER ,
    runs_off_bat    INTEGER ,
    extras    INTEGER ,
    wides   INTEGER ,
    noballs   INTEGER ,
    byes    INTEGER ,
    legbyes   INTEGER ,
    penalty   INTEGER ,
    wicket_type   VARCHAR(200)  ,
    dismissed_player_id    INTEGER,
    PRIMARY KEY (match_id, innings_no, ball_no),
    FOREIGN KEY (match_id, innings_no) REFERENCES innings(match_id, innings_no),
    FOREIGN KEY (striker_id) REFERENCES player(player_id),
    FOREIGN KEY (non_striker_id) REFERENCES player(player_id),
    FOREIGN KEY (bowler_id) REFERENCES player(player_id),
    FOREIGN KEY (dismissed_player_id) REFERENCES player(player_id)
);


INSERT INTO score_by_ball VALUES(1,1,0.1,1,2,21,0,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,0.2,1,2,21,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,0.3,2,1,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,0.4,2,1,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,0.5,2,1,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,0.6,2,1,21,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,0.7,2,1,21,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,1.1,2,1,23,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,1.2,2,1,23,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,1.3,2,1,23,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,1.4,2,1,23,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,1.5,2,1,23,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,1.6,2,1,23,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,2.1,2,1,21,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,2.2,2,1,21,0,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,2.3,2,1,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,2.4,2,1,21,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,2.5,2,1,21,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,2.6,2,1,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,2.7,2,1,21,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,3.1,1,2,22,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,3.2,1,2,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,3.3,2,1,22,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,3.4,2,1,22,0,1,NULL,NULL,1,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,3.5,1,2,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,3.6,2,1,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,4.1,2,1,24,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,4.2,2,1,24,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,4.3,2,1,24,0,0,NULL,NULL,NULL,NULL,NULL,'caught',2);
INSERT INTO score_by_ball VALUES(1,1,4.4,3,1,24,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,4.5,3,1,24,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,4.6,3,1,24,0,0,NULL,NULL,NULL,NULL,NULL,'caught',3);
INSERT INTO score_by_ball VALUES(1,1,5.1,1,4,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,5.2,1,4,21,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,5.3,4,1,21,0,0,NULL,NULL,NULL,NULL,NULL,'caught',4);
INSERT INTO score_by_ball VALUES(1,1,5.4,5,1,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,5.5,5,1,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,5.6,5,1,21,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,6.1,1,5,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,6.2,5,1,18,2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,6.3,5,1,18,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,6.4,5,1,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,6.5,1,5,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,6.6,5,1,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,7.1,5,1,22,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,7.2,5,1,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);






INSERT INTO score_by_ball VALUES(1,1,7.3,1,5,22,2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,7.4,1,5,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,7.5,5,1,22,2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,7.6,5,1,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,8.1,5,1,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,8.2,1,5,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,8.3,5,1,18,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,8.4,5,1,18,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,8.5,5,1,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,8.6,1,5,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,9.1,1,5,22,2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,9.2,1,5,22,6,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,9.3,1,5,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,9.4,5,1,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,9.5,1,5,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,9.6,5,1,22,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,10.1,5,1,18,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,10.2,5,1,18,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,10.3,5,1,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,10.4,1,5,18,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,10.5,1,5,18,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,10.6,1,5,18,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,11.1,5,1,24,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,11.2,1,5,24,0,0,NULL,NULL,NULL,NULL,NULL,'caught',1);
INSERT INTO score_by_ball VALUES(1,1,11.3,6,5,24,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,11.4,5,6,24,0,0,NULL,NULL,NULL,NULL,NULL,'bowled',5);
INSERT INTO score_by_ball VALUES(1,1,11.5,7,6,24,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,11.6,7,6,24,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,12.1,7,6,23,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,12.2,7,6,23,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,12.3,6,7,23,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,12.4,7,6,23,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,12.5,7,6,23,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,12.6,6,7,23,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,13.1,6,7,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,13.2,7,6,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,13.3,6,7,18,2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,13.4,6,7,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,13.5,7,6,18,0,1,NULL,NULL,NULL,1,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,13.6,6,7,18,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,14.1,6,7,21,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,14.2,6,7,21,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,14.3,7,6,21,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,14.4,6,7,21,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,1,14.5,7,6,21,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);



INSERT INTO score_by_ball VALUES(1,2,15.4,17,18,5,3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,15.5,18,17,5,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,15.6,17,18,5,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,15.7,18,17,5,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,16.1,18,17,9,2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,16.2,18,17,9,2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,16.3,18,17,9,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,16.4,17,18,9,0,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,16.5,17,18,9,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,16.6,17,18,9,0,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,16.7,17,18,9,0,4,NULL,NULL,4,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,16.8,17,18,9,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,17.1,17,18,11,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,17.2,17,18,11,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,17.3,17,18,11,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,17.4,17,18,11,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,17.5,17,18,11,4,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,17.6,17,18,11,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,18.1,18,17,9,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,18.2,17,18,9,0,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,18.3,17,18,9,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,18.4,17,18,9,6,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO score_by_ball VALUES(1,2,18.5,17,18,9,0,4,NULL,NULL,NULL,4,NULL,NULL,NULL);

SELECT * FROM score_by_ball;


-- Create the result table
CREATE TABLE result
(   match_id    INTEGER NOT NULL PRIMARY KEY,
    winning_team_id INTEGER NOT NULL,         
    player_of_the_match_id   INTEGER NOT NULL ,
    FOREIGN KEY (match_id) REFERENCES `match`(match_id),
    FOREIGN KEY (winning_team_id) REFERENCES team(team_id),
    FOREIGN KEY (player_of_the_match_id) REFERENCES player(player_id)
);

